# FinanceDataReader

In [2]:
# !pip install -U finance-datareader

Collecting finance-datareader
  Downloading finance_datareader-0.9.12-py3-none-any.whl (13 kB)
Requirement already satisfied, skipping upgrade: lxml in c:\users\junghyundo\anaconda3\lib\site-packages (from finance-datareader) (4.5.2)
Collecting requests-file
  Downloading requests_file-1.5.1-py2.py3-none-any.whl (3.7 kB)
Requirement already satisfied, skipping upgrade: tqdm in c:\users\junghyundo\anaconda3\lib\site-packages (from finance-datareader) (4.47.0)
Requirement already satisfied, skipping upgrade: requests>=2.3.0 in c:\users\junghyundo\anaconda3\lib\site-packages (from finance-datareader) (2.24.0)
Requirement already satisfied, skipping upgrade: pandas>=0.19.2 in c:\users\junghyundo\anaconda3\lib\site-packages (from finance-datareader) (1.0.5)
Requirement already satisfied, skipping upgrade: six in c:\users\junghyundo\anaconda3\lib\site-packages (from requests-file->finance-datareader) (1.15.0)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\junghyundo\anaconda3\lib\site-packages (from requests>=2.3.0->finance-datareader) (2020.6.20)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in c:\users\junghyundo\anaconda3\lib\site-packages (from requests>=2.3.0->finance-datareader) (2.10)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in c:\users\junghyundo\anaconda3\lib\site-packages (from requests>=2.3.0->finance-datareader) (3.0.4)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\junghyundo\anaconda3\lib\site-packages (from requests>=2.3.0->finance-datareader) (1.25.9)
Requirement already satisfied, skipping upgrade: numpy>=1.13.3 in c:\users\junghyundo\anaconda3\lib\site-packages (from pandas>=0.19.2->finance-datareader) (1.18.5)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in c:\users\junghyundo\anaconda3\lib\site-packages (from pandas>=0.19.2->finance-datareader) (2020.1)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in c:\users\junghyundo\anaconda3\lib\site-packages (from pandas>=0.19.2->finance-datareader) (2.8.1)
Installing collected packages: requests-file, finance-datareader
Successfully installed finance-datareader-0.9.12 requests-file-1.5.1

## 3. 라이브러리 불러오기

In [5]:
# 분석을 위한 pandas call
import pandas as pd

In [6]:
# fdr 이란 이름으로 불러옴

import FinanceDataReader as fdr

fdr.__version__

'0.9.12'

## 4. 한국거래소 상장 종목 전체 가져오기

In [8]:
# 도움말을 보고자 할때는? 를 사용하고 , 소스코드를 볼때는 ??를 사용합니다
# 주피터 노트북에서는 함수나 메소드의 괄호안에서 shift + tab 키를 누르면 도움말을 볼 수 있습니다

# fdr.StockListing??

In [9]:
# KRX : KRX 종목 전체
# KOSPI : ~의 종목
# KOSDAQ - 코스닥
# KONEX - 코넥스
# NASDAQ - 나스닥
# NYSE - 뉴욕증권거래소
# SP500 -= S&P 500 종목

In [11]:
# 한국거래소 상장종목 전체 가져오기

df_krx = fdr.StockListing("KRX")
df_krx.shape

(2612, 10)

In [12]:
# 행과 열의 크기를 확인 (행, 열) 순서
df_krx.shape

(2612, 10)

In [14]:
# 전체 데이터 프레임으 ㅣ요약정보를 확인
# 2612개의 행이 있음., 10개의 컬럼으로 구성되어있음
# non-null ( 결측치를 제외한 값들의 갯수)
# ListingDate 를 제외한 나머지는 object(문자) 타입니다
# 파이썬의 인덱스는 0부터 시작함
#
df_krx.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2612 entries, 0 to 2611
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Symbol          2612 non-null   object
 1   Market          2612 non-null   object
 2   Name            2612 non-null   object
 3   Sector          2411 non-null   object
 4   Industry        2392 non-null   object
 5   ListingDate     2411 non-null   datetime64[ns]
 6   SettleMonth     2411 non-null   object
 7   Representative  2411 non-null   object
 8   HomePage        2239 non-null   object
 9   Region          2411 non-null   object
dtypes: datetime64[ns](1), object(9)
memory usage: 224.5+ KB

In [15]:
# 기술통계 값을 요약한다
df_krx.describe()
# index/ count - 빈도수, unique - 중복되지 않은값
# top - 가장 빈번하게 등장하는 문자열이 무멋인가 (랜덤하게 1개)
# freq  top에 대한 빈도수
# sector ( 
# industry (산업군)
# first, last  - Listingdate - 첫 상장된 종목의 날짜, 마지막 날짜

,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
count,2612,2612,2612,2411,2392,2411,2411,2411,2239,2411
unique,2612,3,2612,158,2240,1777,9,2297,2218,21
top,004430,KOSDAQ,국보,특수 목적용 기계 제조업,기업인수합병,1976-06-30 00:00:00,12월,이재원,http://www.moorim.co.kr,서울특별시
freq,1,1471,1,141,37,8,2351,4,2,969
first,NaN,NaN,NaN,NaN,NaN,1956-03-03 00:00:00,NaN,NaN,NaN,NaN
last,NaN,NaN,NaN,NaN,NaN,2020-12-30 00:00:00,NaN,NaN,NaN,NaN

## 5. 파일로 저장하고 불러오기

In [18]:
df_krx.head()

,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,060310,KOSDAQ,3S,특수 목적용 기계 제조업,반도체 웨이퍼 캐리어,2002-04-23,03월,"박종익, 김세완 (각자 대표이사)",http://www.3sref.com,서울특별시
1,095570,KOSPI,AJ네트웍스,산업용 기계 및 장비 임대업,"렌탈(파렛트, OA장비, 건설장비)",2015-08-21,12월,이현우,http://www.ajnet.co.kr,서울특별시
2,006840,KOSPI,AK홀딩스,기타 금융업,지주사업,1999-08-11,12월,"채형석, 이석주(각자 대표이사)",http://www.aekyunggroup.co.kr,서울특별시
3,054620,KOSDAQ,APS홀딩스,기타 금융업,인터넷 트래픽 솔루션,2001-12-04,12월,정기로,http://www.apsholdings.co.kr,경기도
4,265520,KOSDAQ,AP시스템,특수 목적용 기계 제조업,디스플레이 제조 장비,2017-04-07,12월,김영주,http://www.apsystems.co.kr,경기도

In [19]:
# to_csv 로 dataframe을 데이터 저장용 파일인  csv 파일로 바꿀 수 있습니다.

df_krx.to_csv("krx.csv", index = False)

In [20]:
# csv로 저장된 파일을 다시 DataFrame으로 읽어서 확인해봅시다
pd.read_csv("krx.csv")

,Symbol,Market,Name,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,060310,KOSDAQ,3S,특수 목적용 기계 제조업,반도체 웨이퍼 캐리어,2002-04-23,03월,"박종익, 김세완 (각자 대표이사)",http://www.3sref.com,서울특별시
1,095570,KOSPI,AJ네트웍스,산업용 기계 및 장비 임대업,"렌탈(파렛트, OA장비, 건설장비)",2015-08-21,12월,이현우,http://www.ajnet.co.kr,서울특별시
2,006840,KOSPI,AK홀딩스,기타 금융업,지주사업,1999-08-11,12월,"채형석, 이석주(각자 대표이사)",http://www.aekyunggroup.co.kr,서울특별시
3,054620,KOSDAQ,APS홀딩스,기타 금융업,인터넷 트래픽 솔루션,2001-12-04,12월,정기로,http://www.apsholdings.co.kr,경기도
4,265520,KOSDAQ,AP시스템,특수 목적용 기계 제조업,디스플레이 제조 장비,2017-04-07,12월,김영주,http://www.apsystems.co.kr,경기도
...,...,...,...,...,...,...,...,...,...,...
2607,000547,KOSPI,흥국화재2우B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2608,000545,KOSPI,흥국화재우,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2609,003280,KOSPI,흥아해운,해상 운송업,외항화물운송업(케미컬탱커),1976-06-29,12월,이환구,http://www.heung-a.com,서울특별시
2610,037440,KOSDAQ,희림,"건축기술, 엔지니어링 및 관련 기술 서비스업",설계 및 감리용역,2000-02-03,12월,"정영균, 이목운, 허철호, 염두성 (각자대표)",http://www.heerim.com,서울특별시
2611,238490,KOSDAQ,힘스,특수 목적용 기계 제조업,"OLED Mask 인장기, OLED Mask 검사기 등",2017-07-20,12월,김주환,http://www.hims.co.kr,인천광역시